#!/bin/sh
### BEGIN INIT INFO
# Provides:          startall
# Required-Start:
# Required-Stop: 
# Default-Start:     S
# Default-Stop:
# Short-Description: do all system init stuff
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

mkdir -p /dev/pts
#mkdir -p /dev/shm
mount -a

if [ -e /proc/cpu/alignment ]; then
   echo "3" > /proc/cpu/alignment
fi

hostname -F /etc/hostname

: exit 0

