#!/bin/sh
### BEGIN INIT INFO
# Provides:          stopall
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0 6
# Short-Description: do all system exit stuff
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

umount -a -r

: exit 0
